// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Sentence = 3,
  WaterproofTactic = 4,
  TacticEnd = 5,
  TacticInput = 6,
  WaterproofByTactic = 7,
  TacticByInput = 8,
  TacticByMiddle = 9,
  TacticByEnd = 10,
  Lemma = 11,
  LemmaStatement = 12,
  LemmaEnd = 13
