// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  BlockComment = 1,
  Program = 2,
  Identifier = 3,
  String = 4,
  Boolean = 5,
  Vernacular = 9,
  Gallina = 10
