// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  TakeInput = 1,
  Comment = 2,
  Program = 3,
  Sentence = 4,
  WaterproofTactic = 5,
  TacticInput = 6,
  TacticEnd = 7,
  Lemma = 8,
  LemmaStatement = 9,
  LemmaEnd = 10
