name: Test installation script

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v3

      - name: Run installation script
        run: sudo ./install.sh